const PDFDocument = require('pdfkit');
const fs = require('fs');

function generateInvoicePDF(invoice, outputPath) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = fs.createWriteStream(outputPath);

    doc.pipe(stream);

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text('INVOICE', 50, 50);
    doc.fontSize(10).font('Helvetica').fillColor('#666')
      .text(`Invoice #: ${invoice.invoice_number}`, 50, 80)
      .text(`Date: ${new Date(invoice.created_at).toLocaleDateString()}`, 50, 95)
      .text(`PO #: ${invoice.po_number}`, 50, 110)
      .text(`RFQ #: ${invoice.rfq_number || 'N/A'}`, 50, 125);

    // Status badge
    doc.fontSize(12).font('Helvetica-Bold').fillColor(
      invoice.status === 'paid' ? '#22c55e' :
      invoice.status === 'sent' ? '#3b82f6' :
      invoice.status === 'overdue' ? '#ef4444' : '#6b7280'
    ).text(invoice.status.toUpperCase(), 450, 50, { align: 'right' });

    // Divider
    doc.moveTo(50, 150).lineTo(545, 150).strokeColor('#ddd').lineWidth(1).stroke();

    // Vendor Info
    doc.fillColor('#000').fontSize(12).font('Helvetica-Bold').text('Bill To:', 50, 170);
    doc.fontSize(10).font('Helvetica').fillColor('#333')
      .text(invoice.vendor_name || 'N/A', 50, 188)
      .text(invoice.contact_person || '', 50, 203)
      .text(invoice.vendor_email || '', 50, 218)
      .text(invoice.vendor_phone || '', 50, 233)
      .text(invoice.vendor_address || '', 50, 248);

    if (invoice.gst_number) {
      doc.text(`GST: ${invoice.gst_number}`, 50, 263);
    }

    // Table header
    let y = 300;
    const tableTop = y;

    doc.fontSize(10).font('Helvetica-Bold').fillColor('#fff');
    doc.rect(50, y, 495, 25).fill('#1a1a2e');
    doc.fillColor('#fff').text('Item', 55, y + 7, { width: 180 })
      .text('Qty', 240, y + 7, { width: 60, align: 'center' })
      .text('Unit Price', 305, y + 7, { width: 80, align: 'right' })
      .text('Total', 430, y + 7, { width: 110, align: 'right' });

    y += 30;

    // Table rows
    doc.font('Helvetica').fillColor('#333');
    if (invoice.items && invoice.items.length > 0) {
      invoice.items.forEach((item, idx) => {
        const bg = idx % 2 === 0 ? '#f9f9f9' : '#fff';
        doc.rect(50, y, 495, 22).fill(bg);
        doc.fillColor('#333')
          .text(item.product_name, 55, y + 5, { width: 180 })
          .text(String(item.quantity), 240, y + 5, { width: 60, align: 'center' })
          .text(`₹${Number(item.unit_price).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 305, y + 5, { width: 80, align: 'right' })
          .text(`₹${Number(item.total_price).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 430, y + 5, { width: 110, align: 'right' });
        y += 22;
      });
    }

    // Totals
    y += 10;
    doc.moveTo(320, y).lineTo(545, y).strokeColor('#ddd').stroke();
    y += 10;

    doc.font('Helvetica').fontSize(10).fillColor('#333')
      .text('Subtotal:', 340, y, { width: 90, align: 'right' })
      .text(`₹${Number(invoice.subtotal).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 430, y, { width: 110, align: 'right' });

    y += 20;
    doc.text(`Tax (${invoice.tax_rate || 18}%):`, 340, y, { width: 90, align: 'right' })
      .text(`₹${Number(invoice.tax_amount).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 430, y, { width: 110, align: 'right' });

    y += 10;
    doc.moveTo(320, y).lineTo(545, y).strokeColor('#1a1a2e').lineWidth(2).stroke();
    y += 10;

    doc.font('Helvetica-Bold').fontSize(13).fillColor('#1a1a2e')
      .text('Total:', 340, y, { width: 90, align: 'right' })
      .text(`₹${Number(invoice.total).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 430, y, { width: 110, align: 'right' });

    // Footer
    const pageHeight = doc.page.height;
    doc.fontSize(8).font('Helvetica').fillColor('#999')
      .text('Generated by VendorBridge — Procurement & Vendor Management ERP', 50, pageHeight - 50, { align: 'center', width: 495 });

    doc.end();

    stream.on('finish', () => resolve(outputPath));
    stream.on('error', reject);
  });
}

module.exports = { generateInvoicePDF };
